apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ape4rcvuf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ape4rcvuf-java-springboot-gitops